FROM alpine:3.22

RUN apk add --no-cache \
    git \
    docker-cli \
    docker-cli-compose \
    openssh-client

  # I push this image to Docker Hub as "mohd7895k/expense-tracker-jenkins-agent:latest" for use in Jenkins pipelines as agent.